- name: Configure hosts & deploy application
  hosts: app
  become: true
  tasks:
    - name: Install git
      apt:
        name:
        - git
        - bundler
        state: present
        update_cache: yes
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma
    - name: Bundle Install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
