- name: Configure hosts & deploy application
  hosts: all
  become: true
  roles:
    - role: app
      tags:
        - appinstall
  tasks:
  - name: Install ruby and bundler
    apt:
      name:
        - ruby-full
        - ruby-bundler
        - build-essential
      state: present
      update_cache: yes
