---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: "158.160.61.146:27017"
  tasks:
    - name:  daemon_reload
      become: true
      systemd: daemon_reload=true
      tags:
      - app-tag
      - db-tag
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
    - name: enable puma
      become: true
      systemd: name=puma daemon_reload=true enabled=yes
      tags: app-tag
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag
    - name: Install git
      become: true
      apt:
        name:
        - git
        - bundler
        state: present
        update_cache: yes
      tags: deploy-tag
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    - name: Bundle Install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag


  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
